// <auto-generated />
#nullable disable

namespace uk.osric.copilot.Migrations {
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
    using uk.osric.copilot.Data;

    [DbContext(typeof(CopilotDbContext))]
    partial class CopilotDbContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("uk.osric.copilot.Models.Session", b => {
                b.Property<string>("Id")
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<string>("LastActiveAt")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("last_active_at");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("title");

                b.Property<string>("WorkingDirectory")
                    .HasColumnType("TEXT")
                    .HasColumnName("working_directory");

                b.HasKey("Id");

                b.ToTable("sessions", (string)null);
            });

            modelBuilder.Entity("uk.osric.copilot.Models.SessionMessage", b => {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("event_type");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("payload");

                b.Property<string>("SessionId")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("session_id");

                b.HasKey("Id");

                b.HasIndex("SessionId")
                    .HasDatabaseName("IX_messages_session_id");

                b.ToTable("messages", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
